//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFTSDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PFTSDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无效的登录请求 的本地化字符串。
        /// </summary>
        internal static string LoginViewModel_Exception_CannotLogin {
            get {
                return ResourceManager.GetString("LoginViewModel_Exception_CannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能为空 的本地化字符串。
        /// </summary>
        internal static string Operator_Error_MissAccount {
            get {
                return ResourceManager.GetString("Operator_Error_MissAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string Operator_Error_MissPasswprd {
            get {
                return ResourceManager.GetString("Operator_Error_MissPasswprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string Suspect_Error_MissName {
            get {
                return ResourceManager.GetString("Suspect_Error_MissName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 案卷号 不能为空 的本地化字符串。
        /// </summary>
        internal static string Suspect_Error_MissNo {
            get {
                return ResourceManager.GetString("Suspect_Error_MissNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责民警不能为空 的本地化字符串。
        /// </summary>
        internal static string Suspect_Error_MissOfficer {
            get {
                return ResourceManager.GetString("Suspect_Error_MissOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RFID服装不能为空 的本地化字符串。
        /// </summary>
        internal static string Suspect_Error_MissVest {
            get {
                return ResourceManager.GetString("Suspect_Error_MissVest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 马甲名称不能为空 的本地化字符串。
        /// </summary>
        internal static string Vest_Error_MissName {
            get {
                return ResourceManager.GetString("Vest_Error_MissName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 马甲识别码不能为空 的本地化字符串。
        /// </summary>
        internal static string Vest_Error_MissNo {
            get {
                return ResourceManager.GetString("Vest_Error_MissNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在重名马甲名称 的本地化字符串。
        /// </summary>
        internal static string Vest_Error_ReName {
            get {
                return ResourceManager.GetString("Vest_Error_ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在重名识别码 的本地化字符串。
        /// </summary>
        internal static string Vest_Error_ReNo {
            get {
                return ResourceManager.GetString("Vest_Error_ReNo", resourceCulture);
            }
        }
    }
}
